---
title: "Pan_Cancer_PTEN_SCNA_status"
author: "William"
date: '2022-06-16'
output: pdf_document
---

```{r setup, include=FALSE}
library(DESeq2)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(pheatmap)
library(ggrepel)
library(ggsignif)
library(ggpubr)
library(annotables)
library(marray)
library(clusterProfiler)
library(org.Hs.eg.db)
library(ensembldb)
library(msigdbr)
library(GSEABase)
library(ggnewscale)
library(vidger)
library(grid)
library(tidyverse)
library(shadowtext)

```

```{r}
RNA_raw_count <- read.csv("TCGA_prostate//Data/Coding_genes_counts_TCGA_prostate.txt", 
                          header = T, sep = "\t")
RNA_raw_count_names <- read.csv("TCGA_prostate/Data/Coding_genes_counts_TCGA_prostate.txt", 
                          header = T, sep = "\t")
all(rownames(RNA_raw_count) == rownames(RNA_raw_count_names))
cols_to_keep <- intersect(rownames(RNA_raw_count), rownames(RNA_raw_count_names))
RNA_raw_count <- RNA_raw_count[cols_to_keep, , drop=FALSE]

metadata <- read.csv("TCGA_prostate/Data/metadata_PTEN_SCNA_status.txt", 
                     header = T, sep = "\t")
metadata <- metadata %>%
  dplyr::mutate(PTEN_SCNA_status = str_replace(metadata$PTEN_SCNA_status, "PTEN-intact", "Intact"))
metadata <- metadata %>%
  dplyr::mutate(PTEN_SCNA_status = str_replace(metadata$PTEN_SCNA_status, "PTEN-HemDelzygLoss", "HemDel"))
metadata <- metadata %>%
  dplyr::mutate(PTEN_SCNA_status = str_replace(metadata$PTEN_SCNA_status, "PTEN-HomDelzygLoss", "HomDel"))

meta_names <- str_replace_all(metadata$Sample, pattern = "[-]", replacement = ".")
rownames(metadata) <- metadata$X.2

```

```{r include=FALSE}
metadata <- metadata %>%
  arrange(PTEN_SCNA_status)
  ###---Creating the index and matching the tables
idx <- match(rownames(metadata), colnames(RNA_raw_count))
RNA_raw_count <- RNA_raw_count[ ,idx]

###---DESeq object(Count matrix, metadata, and design formula)---
dds_rna <- DESeqDataSetFromMatrix(RNA_raw_count, 
                                  colData = metadata, 
                                  design  = ~ PTEN_SCNA_status)
###---Relevel of the design factor---
#use the factor of interest after '$'
dds_rna$PTEN_SCNA_status <- relevel(dds_rna$PTEN_SCNA_status, ref = "Intact")
  ###---Running DESeq2---
dds_DESeq <- DESeq(dds_rna, parallel = T)

plotDispEsts(dds_DESeq)
```

```{r echo=FALSE}
vsd <- varianceStabilizingTransformation(dds_DESeq, blind = F)
  ###--converts the data in a DESeqTransform object to a simple 2-dimensional 
  ##data structure
vsd_mat <- assay(vsd)
##Compute pairwise correlation
#vsd_cor <- cor(vsd_mat)

meta <- dplyr::select(metadata, c(PTEN_SCNA_status))


# heatmap <- pheatmap(vsd_cor, annotation_col = meta,
#          show_rownames = F,
#          show_colnames = F,
#          main = "Hierarchical clustering - Correlation")

###---PCA object to use in ggplot2
#pca <- plotPCA(vsd, intgroup = c("PTEN_SCNA_status"), returnData = T)
pca <- plotPCA(vsd, intgroup = c("PTEN_SCNA_status"))

```


```{r}
resultsNames(dds_DESeq)
```

```{r include=FALSE}

result_shrink_Hemi_vs_Intact <- lfcShrink(dds_DESeq, coef = "PTEN_SCNA_status_HemDel_vs_Intact",
                                            type = "apeglm", parallel = T)
result_shrink_Homo_vs_Intact <- lfcShrink(dds_DESeq, coef = "PTEN_SCNA_status_HomDel_vs_Intact",
                                            type = "apeglm", parallel = T)
result_shrink_Dupl_vs_Intact <- lfcShrink(dds_DESeq, coef = "PTEN_SCNA_status_Dupl_vs_Intact",
                                            type="apeglm" )


print(summary(result_shrink_Hemi_vs_Intact, alpha = 0.05))
  
print(summary(result_shrink_Homo_vs_Intact, alpha = 0.05))
  
print(summary(result_shrink_Dupl_vs_Intact, alpha = 0.05))

```

```{r echo=FALSE}
padj.cutoff_0.05 <- 0.05

tx2gene <- annotables::grch38
grch38annot <- tx2gene %>% 
  dplyr::select(symbol, description, biotype, ensgene, entrez) %>% 
  dplyr::distinct()

res_0.05_shrink_Hemi_vs_Intac_tb <- result_shrink_Hemi_vs_Intact %>%
  as.data.frame() %>%
  rownames_to_column(var = "gene") %>%
  dplyr::filter(padj < padj.cutoff_0.05)  %>%
  arrange(padj) %>%
  left_join(grch38annot, by = c("gene"= "ensgene")) %>%
  distinct(gene, .keep_all = T)
  
res_0.05_shrink_Homo_vs_Intact_tb <- result_shrink_Homo_vs_Intact %>%
  as.data.frame() %>%
  rownames_to_column(var = "gene") %>%
  dplyr::filter(padj < padj.cutoff_0.05)  %>%
  arrange(padj) %>%
  left_join(grch38annot, by = c("gene"= "ensgene")) %>%
  distinct(gene, .keep_all = T)

res_0.05_shrink_Dupl_vs_Intact_tb <- result_shrink_Dupl_vs_Intact %>%
  data.frame() %>%
  rownames_to_column(var = "gene") %>%
  dplyr::filter(padj < padj.cutoff_0.05)%>%
  arrange(padj) %>%
  left_join(grch38annot, by = c("gene"= "ensgene")) %>%
  distinct(gene, .keep_all = T)

write_tsv(res_0.05_shrink_Hemi_vs_Intac_tb, "TCGA_brain/Results/brain/res_Hemi_padj_0.05_Brain.txt",
            col_names = T)
write_tsv(res_0.05_shrink_Homo_vs_Intact_tb, "TCGA_brain/Results/brain/res_Hom_padj_0.05_Brain.txt",
            col_names = T)
write_tsv(res_0.05_shrink_Dupl_vs_Intact_tb, "TCGA_brain/Results/brain/res_Dup_padj_0.05_Brain.txt",
            col_names = T)

```



```{r}
#Volcano plot PTEN Hemizygous loss
res_0.05_shrink_Hemi_vs_Intac_tb$DEGs <- "padj > 0.05"
res_0.05_shrink_Hemi_vs_Intac_tb$DEGs[res_0.05_shrink_Hemi_vs_Intac_tb$log2FoldChange > 0.58 & 
                                                 res_0.05_shrink_Hemi_vs_Intac_tb$padj < 0.05] <- "padj < 0.05; lfc > 1.5"
res_0.05_shrink_Hemi_vs_Intac_tb$DEGs[res_0.05_shrink_Hemi_vs_Intac_tb$log2FoldChange < -0.58 & 
                                                 res_0.05_shrink_Hemi_vs_Intac_tb$padj < 0.05] <- "padj < 0.05; lfc < -1.5"

mycolors <- c("dodgerblue3", "firebrick3", "gainsboro")
names(mycolors) <- c("padj < 0.05; lfc < -1.5", "padj < 0.05; lfc > 1.5", "padj > 0.05")

res_0.05_shrink_Hemi_vs_Intac_tb$delabel <- NA
res_0.05_shrink_Hemi_vs_Intac_tb$delabel[res_0.05_shrink_Hemi_vs_Intac_tb$DEGs != "padj > 0.05"] <- res_0.05_shrink_Hemi_vs_Intac_tb$symbol[res_0.05_shrink_Hemi_vs_Intac_tb$DEGs != "padj > 0.05"]

p_hemi <- ggplot(data = res_0.05_shrink_Hemi_vs_Intac_tb, aes(x = log2FoldChange, y = -log10(padj), 
                                                         col = DEGs, label = delabel)) + 
  geom_point() + 
  theme_minimal() + 
  geom_vline(xintercept = c(-0.58, 0.58), col = "red") +
  geom_hline(yintercept= -log10(0.05), col = "red") +
  scale_colour_manual(values = mycolors) +
  geom_text_repel(max.overlaps = 5) +
  theme(legend.position = "none") +
  ylim(c(0,30))

#Volcano Plot PTEN Homozygous loss
res_0.05_shrink_Homo_vs_Intact_tb$DEGs <- "padj > 0.05"
res_0.05_shrink_Homo_vs_Intact_tb$DEGs[res_0.05_shrink_Homo_vs_Intact_tb$log2FoldChange > 0.58 &
                                                 res_0.05_shrink_Homo_vs_Intact_tb$padj < 0.05] <- "padj < 0.05; lfc > 1.5"
res_0.05_shrink_Homo_vs_Intact_tb$DEGs[res_0.05_shrink_Homo_vs_Intact_tb$log2FoldChange < -0.58 &
                                                 res_0.05_shrink_Homo_vs_Intact_tb$padj < 0.05] <- "padj < 0.05; lfc < -1.5"

res_0.05_shrink_Homo_vs_Intact_tb$delabel <- NA
res_0.05_shrink_Homo_vs_Intact_tb$delabel[res_0.05_shrink_Homo_vs_Intact_tb$DEGs != "padj > 0.05"] <- res_0.05_shrink_Homo_vs_Intact_tb$symbol[res_0.05_shrink_Homo_vs_Intact_tb$DEGs != "padj > 0.05"]

p_homo <- ggplot(data = res_0.05_shrink_Homo_vs_Intact_tb, aes(x = log2FoldChange, y = -log10(padj),
                                                         col = DEGs, label = delabel)) +
  geom_point() +
  theme_minimal() +
  geom_vline(xintercept = c(-0.58, 0.58), col = "red") +
  geom_hline(yintercept= -log10(0.05), col = "red") +
  scale_colour_manual(values = mycolors) +
  geom_text_repel(max.overlaps = 5) +
  theme(legend.position = "none") +
  ylim(c(0,30))

#Volcano Plot PTEN duplicated
res_0.05_shrink_Dupl_vs_Intact_tb$DEGs <- "padj > 0.05"
res_0.05_shrink_Dupl_vs_Intact_tb$DEGs[res_0.05_shrink_Dupl_vs_Intact_tb$log2FoldChange > 0.58 &
                                                  res_0.05_shrink_Dupl_vs_Intact_tb$padj < 0.05] <- "padj < 0.05; lfc > 1.5"
res_0.05_shrink_Dupl_vs_Intact_tb$DEGs[res_0.05_shrink_Dupl_vs_Intact_tb$log2FoldChange < -0.58 &
                                                  res_0.05_shrink_Dupl_vs_Intact_tb$padj < 0.05] <- "padj < 0.05; lfc < -1.5"

res_0.05_shrink_Dupl_vs_Intact_tb$delabel <- NA
res_0.05_shrink_Dupl_vs_Intact_tb$delabel[res_0.05_shrink_Dupl_vs_Intact_tb$DEGs != "padj > 0.05"] <- res_0.05_shrink_Dupl_vs_Intact_tb$symbol[res_0.05_shrink_Dupl_vs_Intact_tb$DEGs != "padj > 0.05"]

p_dupl <- ggplot(data = res_0.05_shrink_Dupl_vs_Intact_tb, aes(x = log2FoldChange, y = -log10(padj),
                                                      col = DEGs, label = delabel)) +
   geom_point() +
   theme_minimal() +
   geom_vline(xintercept = c(-0.58, 0.58), col = "red") +
   geom_hline(yintercept= -log10(0.05), col = "red") +
   scale_colour_manual(values = mycolors) +
   geom_text_repel(max.overlaps = 5) +
   theme(legend.key.size = unit(2, "mm"),
         legend.text = element_text(size = 6),
         legend.title = element_text(size = 7)) +
   ylim(c(0,30))

all_volcano <- ggarrange(p_hemi, p_homo, p_dupl, ncol = 3, labels = "AUTO")

```


```{r echo=FALSE}
vsd_mat_tb <- vsd_mat %>% as.data.frame() %>%
  rownames_to_column(var = "gene") %>%
  left_join(grch38annot, by = c("gene" = "ensgene")) %>%
  distinct(gene, .keep_all = T)
  
vsd_mat_Hem <- vsd_mat_tb %>% 
  dplyr::filter(gene %in% res_0.05_shrink_Hemi_vs_Intac_tb$gene) %>%
  distinct(symbol, .keep_all = T) %>%
  left_join(res_0.05_shrink_Hemi_vs_Intac_tb, by = c("gene" = "gene")) %>%
  dplyr::filter(abs(log2FoldChange) > 0.58) %>%
  dplyr::arrange(padj) %>%
  drop_na(symbol.x)
rownames(vsd_mat_Hem) <- vsd_mat_Hem$symbol.x

vsd_mat_Hom <- vsd_mat_tb %>%
  dplyr::filter(gene %in% res_0.05_shrink_Homo_vs_Intact_tb$gene) %>%
  distinct(symbol, .keep_all = T) %>%
  left_join(res_0.05_shrink_Homo_vs_Intact_tb, by = c("gene" = "gene")) %>%
  dplyr::filter(abs(log2FoldChange) > 0.58) %>%
  dplyr::arrange(padj) %>%
  drop_na(symbol.x)
rownames(vsd_mat_Hom) <- vsd_mat_Hom$symbol.x

vsd_mat_dup <- vsd_mat_tb %>%
  dplyr::filter(gene %in% res_0.05_shrink_Dupl_vs_Intact_tb$gene) %>%
  distinct(symbol, .keep_all = T) %>%
  left_join(res_0.05_shrink_Dupl_vs_Intact_tb, by = c("gene" = "gene")) %>%
  dplyr::filter(abs(log2FoldChange) > 0.58) %>%
  dplyr::arrange(padj) %>%
  drop_na(symbol.x)
rownames(vsd_mat_dup) <- vsd_mat_dup$symbol.x

```


```{r}
heat_colors <- maPalette(low = "blue", high = "red", mid = 'white', k = 1000)

meta <- dplyr::select(metadata,PTEN_SCNA_status) %>%
  mutate(count = row_number(PTEN_SCNA_status))

meta2 <- dplyr::select(metadata, c(PTEN_SCNA_status))

#"HomDel","HemDel","Intact"
#"red2", "dodgerblue2", "forestgreen"
```

```{r}
pheatmap(vsd_mat_Hem[1:50, c(4:238, 261:666)], 
         color         = heat_colors,
         cluster_rows  = T,
         cluster_cols  = T, 
         show_rownames = T,
         show_colnames = F,
         annotation = meta2,
         border_color  = NA, 
         fontsize      = 10, 
         scale         = "row", 
         fontsize_row  = 11, 
         height        = 20,
         main          = "TCGA Brain:PTEN_SCNA", 
         annotation_colors = list(PTEN_SCNA_status = c(HemDel = "dodgerblue2",
                                                       Intact = "forestgreen")))

pheatmap(vsd_mat_Hom[1:28, c(239:666)], 
         color         = heat_colors,
         cluster_rows  = T,
         cluster_cols  = T, 
         show_rownames = T,
         show_colnames = F,
         annotation = meta2,
         border_color  = NA, 
         fontsize      = 10, 
         scale         = "row", 
         fontsize_row  = 11, 
         height        = 20,
         main          = "TCGA Brain:PTEN_SCNA",
         annotation_colors = list(PTEN_SCNA_status = c(HomDel = "red2",
                                                       Intact = "forestgreen")))

pheatmap(vsd_mat_dup[1:50, c(2:19, 40:57)],
         color         = heat_colors,
         cluster_rows  = T,
         cluster_cols  = T,
         show_rownames = T,
         show_colnames = F,
         annotation = meta2,
         border_color  = NA,
         fontsize      = 10,
         scale         = "row",
         fontsize_row  = 11,
         height        = 20,
         main          = "TCGA Brain:PTEN_SCNA")

```

```{r}
##Create background dataset for hypergeometric testing using all genes tested for significance in the results
all_genes <- as.character(result_shrink_Hemi_vs_Intact@rownames)

##Extract significant results Hemizygous
sig_Hemi_up <- res_0.05_shrink_Hemi_vs_Intac_tb %>%
  dplyr::filter(res_0.05_shrink_Hemi_vs_Intac_tb$log2FoldChange > 0.58)
sig_Hemi_down <- res_0.05_shrink_Hemi_vs_Intac_tb %>%
  dplyr::filter(res_0.05_shrink_Hemi_vs_Intac_tb$log2FoldChange < 0.58)
sig_genes_Hemi_up <- as.character(sig_Hemi_up$gene)
sig_genes_Hemi_down <- as.character(sig_Hemi_down$gene)

##Extract significant results Homozygous
sig_Homo_up <- res_0.05_shrink_Homo_vs_Intact_tb %>%
  dplyr::filter(res_0.05_shrink_Homo_vs_Intact_tb$log2FoldChange > 0.58)
sig_Homo_down <- res_0.05_shrink_Homo_vs_Intact_tb %>%
  dplyr::filter(res_0.05_shrink_Homo_vs_Intact_tb$log2FoldChange < 0.58)
sig_genes_Homo_up <- as.character(sig_Homo_up$gene)
sig_genes_Homo_down <- as.character(sig_Homo_down$gene)

#Extract significant results Duplication
sig_Dupl_up <- res_0.05_shrink_Dupl_vs_Intact_tb %>%
  dplyr::filter(res_0.05_shrink_Dupl_vs_Intact_tb$log2FoldChange > 0.58)
sig_Dupl_down <- res_0.05_shrink_Dupl_vs_Intact_tb %>%
  dplyr::filter(res_0.05_shrink_Dupl_vs_Intact_tb$log2FoldChange < 0.58)
sig_genes_Dupl_up <- as.character(sig_Dupl_up$gene)
sig_genes_Dupl_down <- as.character(sig_Dupl_down$gene)

##Running OR enrichment analyses Hemizygous loss
ego_hemi_up <- enrichGO(gene  = sig_genes_Hemi_up, 
                   universe = all_genes,
                   keyType  = "ENSEMBL",
                   OrgDb    = org.Hs.eg.db, 
                   ont      = "BP", #Go terms:Biological Process(BP), Cellular Component(CC), Molecular Function(MF), or (ALL)
                   pAdjustMethod = "BH", 
                   qvalueCutoff  = 0.05, 
                   readable = TRUE) #Gives the gene symbol as output(matched with genes IDs)
  
ego_hemi_down <- enrichGO(gene = sig_genes_Hemi_down, 
                     universe = all_genes,
                     keyType  = "ENSEMBL",
                     OrgDb    = org.Hs.eg.db, 
                     ont      = "BP", 
                     pAdjustMethod = "BH", 
                     qvalueCutoff  = 0.05, 
                     readable      = TRUE)

#Running OR enrichment analyses Homozygous loss
ego_homo_up <- enrichGO(gene  = sig_genes_Homo_up,
                    universe = all_genes,
                    keyType  = "ENSEMBL",
                    OrgDb    = org.Hs.eg.db,
                    ont      = "BP", 
                    pAdjustMethod = "BH",
                    qvalueCutoff  = 0.05,
                    readable = TRUE) #Gives the gene symbol as output(matched with genes IDs)

ego_homo_down <- enrichGO(gene = sig_genes_Homo_down,
                    universe = all_genes,
                    keyType  = "ENSEMBL",
                    OrgDb    = org.Hs.eg.db,
                    ont      = "BP",
                    pAdjustMethod = "BH",
                    qvalueCutoff  = 0.05,
                    readable      = TRUE)

#Running OR enrichment analyses Duplication
ego_dupl_up <- enrichGO(gene  = sig_genes_Dupl_up,
                   universe = all_genes,
                   keyType  = "ENSEMBL",
                   OrgDb    = org.Hs.eg.db,
                   ont      = "BP", #Go terms:Biological Process(BP), Cellular Component(CC), Molecular Function(MF), or (ALL)
                   pAdjustMethod = "BH",
                   qvalueCutoff  = 0.05,
                   readable = TRUE) #Gives the gene symbol as output(matched with genes IDs)

ego_dupl_down <- enrichGO(gene = sig_genes_Dupl_down,
                     universe = all_genes,
                     keyType  = "ENSEMBL",
                     OrgDb    = org.Hs.eg.db,
                     ont      = "BP",
                     pAdjustMethod = "BH",
                     qvalueCutoff  = 0.05,
                     readable      = TRUE)


##use 'simplify()' to remove redundant terms in Hemizygous loss
ego_hemi_up_simply <- simplify(ego_hemi_up, cutoff   = 0.7, by = "p.adjust", select_fun = min)
ego_hemi_down_simply <- simplify(ego_hemi_down, cutoff = 0.7, by = "p.adjust", select_fun = min)

ego_homo_up_simply <- simplify(ego_homo_up, cutoff   = 0.7, by = "p.adjust", select_fun = min)
ego_homo_down_simply <- simplify(ego_homo_down, cutoff = 0.7, by = "p.adjust", select_fun = min)

ego_dupl_up_simply <- simplify(ego_dupl_up, cutoff   = 0.7, by = "p.adjust", select_fun = min)
ego_dupl_down_simply <- simplify(ego_dupl_down, cutoff = 0.7, by = "p.adjust", select_fun = min)

##Write in the current directory enriched terms for Hemizygous loss
write_tsv(ego_hemi_up_simply@result, 
            "TCGA_brain/Results/brain/enrichment/c_enrich_GO_BP_Hemi_UP.txt", 
            col_names = TRUE)
write_tsv(ego_hemi_down_simply@result, 
            "TCGA_brain/Results/brain/enrichment/c_enrich_GO_BP_Hemi_DOWN.txt", 
            col_names = TRUE)

#Write in the current directory enriched terms for Homozygous loss
write_tsv(ego_homo_up_simply@result,
            "TCGA_brain/Results/brain/enrichment/c_enrich_GO_BP_Homo_UP.txt",
            col_names = TRUE)
write_tsv(ego_homo_down_simply@result,
            "TCGA_brain/Results/brain/enrichment/c_enrich_GO_BP_Homo_DOWN.txt",
            col_names = TRUE)

##Write in the current directory enriched terms for Duplication
write_tsv(ego_dupl_up_simply@result,
            "TCGA_brain/Results/brain/enrichment/c_enrich_GO_BP_Dupl_UP.txt",
            col_names = TRUE)
write_tsv(ego_dupl_down_simply@result,
            "TCGA_brain/Results/brain/enrichment/c_enrich_GO_BP_Dupl_DOWN.txt",
            col_names = TRUE)
```


```{r}
color_up <- RColorBrewer::brewer.pal(5, name = "YlOrRd")
color_down <-  RColorBrewer::brewer.pal(5, name = "Blues")

#Barplot Hemizygous loss
c_GO_BP_Hemi_up <- ego_hemi_up_simply@result %>%
  mutate(qscore = -log(`pvalue`, base=10)) %>%
  dplyr::arrange(qscore)

c_GO_BP_Hemi_down <- ego_hemi_down_simply@result %>%
  mutate(qscore = -log(`pvalue`, base=10)) %>%
  dplyr::arrange(qscore)

up_hemi <- ggplot(c_GO_BP_Hemi_up[293:303,],
       aes(`qscore`, fct_reorder(Description, `qscore`), fill = `qvalue`)) +
  geom_col() +
  theme_gray() +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.title.y = element_blank(),
        plot.title = element_text(size = 20),
        axis.text.x = element_text(colour = 'black', size = 8),
        legend.position = c(0.9, 0.2),
        legend.key.height = unit(2, "mm")) +
  geom_text(mapping = aes(0, y = Description, label = Description),
            hjust = 0, colour = "black", size = 4) +
  scale_x_continuous(expand = c(0.01,0))+
  scale_y_discrete() +
  scale_fill_gradientn(colours = color_up,
                       guide = guide_colorbar(reverse = F)) +
  xlab("-log10(padj)")

down_hemi <- ggplot(c_GO_BP_Hemi_down[43:53,],
       aes(`qscore`, fct_reorder(Description, `qscore`), fill = `qvalue`)) +
  geom_col() +
  theme_gray() +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.title.y = element_blank(),
        plot.title = element_text(size = 20),
        axis.text.x = element_text(colour = 'black', size = 8),
        legend.position = c(0.9, 0.2),
        legend.key.height = unit(2, "mm")) +
  geom_text(mapping = aes(0, y = Description, label = Description),
            hjust = 0, colour = "black", size = 4) +
  scale_x_continuous(expand = c(0.01,0))+
  scale_y_discrete() +
  scale_fill_gradientn(colours = color_down,
                       guide = guide_colorbar(reverse = F)) +
  xlab("-log10(padj)")

#Barplot Homozygous loss
c_GO_BP_homo_up <- ego_homo_up_simply@result %>%
  mutate(qscore = -log(`pvalue`, base=10)) %>%
  dplyr::arrange(qscore)

c_GO_BP_homo_down <- ego_homo_down_simply@result %>%
  mutate(qscore = -log(`pvalue`, base=10)) %>%
  dplyr::arrange(qscore)

up_homo <- ggplot(c_GO_BP_homo_up[248:258,],
       aes(`qscore`, fct_reorder(Description, `qscore`), fill = `qvalue`)) +
  geom_col() +
  theme_gray() +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.title.y = element_blank(),
        plot.title = element_text(size = 20),
        axis.text.x = element_text(colour = 'black', size = 8),
        legend.position = c(0.9, 0.2),
        legend.key.height = unit(2, "mm")) +
  geom_text(mapping = aes(0, y = Description, label = Description),
            hjust = 0, colour = "black", size = 4) +
  scale_x_continuous(expand = c(0.01,0))+
  scale_y_discrete() +
  scale_fill_gradientn(colours = color_up,
                       guide = guide_colorbar(reverse = F)) +
  xlab("-log10(padj)")

down_homo <- ggplot(c_GO_BP_homo_down[98:108,],
       aes(`qscore`, fct_reorder(Description, `qscore`), fill = `qvalue`)) +
  geom_col() +
  theme_gray() +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.title.y = element_blank(),
        plot.title = element_text(size = 20),
        axis.text.x = element_text(colour = 'black', size = 8),
        legend.position = c(0.9, 0.2),
        legend.key.height = unit(2, "mm")) +
  geom_text(mapping = aes(0, y = Description, label = Description),
            hjust = 0, colour = "black", size = 4) +
  scale_x_continuous(expand = c(0.01,0))+
  scale_y_discrete() +
  scale_fill_gradientn(colours = color_down,
                       guide = guide_colorbar(reverse = F)) +
  xlab("-log10(padj)")

# Barplot Duplicated
c_GO_BP_dupl_up <- ego_dupl_up_simply@result %>%
  mutate(qscore = -log(`pvalue`, base=10)) %>%
  dplyr::arrange(qscore)

c_GO_BP_dupl_down <- ego_dupl_down_simply@result %>%
  mutate(qscore = -log(`pvalue`, base=10)) %>%
  dplyr::arrange(qscore)

up_dupl <- ggplot(c_GO_BP_dupl_up[20:30,],
       aes(`qscore`, fct_reorder(Description, `qscore`), fill = `qvalue`)) +
  geom_col() +
  theme_gray() +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.title.y = element_blank(),
        plot.title = element_text(size = 20),
        axis.text.x = element_text(colour = 'black', size = 8),
        legend.position = c(0.9, 0.2),
        legend.key.height = unit(2, "mm")) +
  geom_text(mapping = aes(0, y = Description, label = Description),
            hjust = 0, colour = "black", size = 4) +
  scale_x_continuous(expand = c(0.01,0))+
  scale_y_discrete() +
  scale_fill_gradientn(colours = color_up,
                       guide = guide_colorbar(reverse = F)) +
  xlab("-log10(padj)")

down_dupl <- ggplot(c_GO_BP_dupl_down[,],
       aes(`qscore`, fct_reorder(Description, `qscore`), fill = `qvalue`)) +
  geom_col() +
  theme_gray() +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.title.y = element_blank(),
        plot.title = element_text(size = 20),
        axis.text.x = element_text(colour = 'black', size = 8),
        legend.position = c(0.9, 0.2),
        legend.key.height = unit(2, "mm")) +
  geom_text(mapping = aes(0, y = Description, label = Description),
            hjust = 0, colour = "black", size = 4) +
  scale_x_continuous(expand = c(0.01,0))+
  scale_y_discrete() +
  scale_fill_gradientn(colours = color_down,
                       guide = guide_colorbar(reverse = F)) +
  xlab("-log10(padj)")

all_enrich <- ggarrange(up_hemi, down_hemi,
                        up_homo, down_homo,
                        up_dupl, down_dupl,
                        nrow = 3, ncol = 2,
                        labels = "AUTO", align = "h", 
                        font.label = list(size = 8))

all_enrich

```

```{r}
name <- "TCGA_Brain"
#Extract the sig. MHC genes from normalized counts matrix 
PTEN <- plotCounts(dds_DESeq, gene = "ENSG00000171862", intgroup = "PTEN_SCNA_status", 
                    returnData = T) 
PTEN <- PTEN %>%
  rownames_to_column(var = "ID") %>%
  mutate(Tumor_type = name, gene = "PTEN", count = log2(count))
colnames(PTEN) <- c("ID", "Count", "PTEN_SCNA_status", "Tumor_type", "Gene")

PDCD1 <- plotCounts(dds_DESeq, gene = "ENSG00000188389", intgroup = "PTEN_SCNA_status", 
                    returnData = T)
PDCD1 <- PDCD1 %>%
  rownames_to_column(var = "ID") %>%
  mutate(Tumor_type = name, gene = "PDCD1", count = log2(count))
colnames(PDCD1) <- c("ID", "Count", "PTEN_SCNA_status", "Tumor_type", "Gene")

CD274 <- plotCounts(dds_DESeq, gene = "ENSG00000120217", intgroup = "PTEN_SCNA_status", 
                    returnData = T)
CD274 <- CD274 %>%
  rownames_to_column(var = "ID") %>%
  mutate(Tumor_type = name, gene = "CD274", count = log2(count))
colnames(CD274) <- c("ID", "Count", "PTEN_SCNA_status", "Tumor_type", "Gene")

CTLA4 <- plotCounts(dds_DESeq, gene = "ENSG00000163599", intgroup = "PTEN_SCNA_status", 
                    returnData = T)
CTLA4 <- CTLA4 %>%
  rownames_to_column(var = "ID") %>%
  mutate(Tumor_type = name, gene = "CTLA4", count = log2(count))
colnames(CTLA4) <- c("ID", "Count", "PTEN_SCNA_status", "Tumor_type", "Gene")

LAG3 <- plotCounts(dds_DESeq, gene = "ENSG00000089692", intgroup = "PTEN_SCNA_status", 
                   returnData = T)
LAG3 <- LAG3 %>%
  rownames_to_column(var = "ID") %>%
  mutate(Tumor_type = name, gene = "LAG3", count = log2(count))
colnames(LAG3) <- c("ID", "Count", "PTEN_SCNA_status", "Tumor_type", "Gene")

IDO1 <- plotCounts(dds_DESeq, gene = "ENSG00000131203", intgroup = "PTEN_SCNA_status", 
                   returnData = T)
IDO1 <- IDO1 %>%
  rownames_to_column(var = "ID") %>%
  mutate(Tumor_type = name, gene = "IDO1", count = log2(count))
colnames(IDO1) <- c("ID", "Count", "PTEN_SCNA_status", "Tumor_type", "Gene")

IFNG <- plotCounts(dds_DESeq, gene = "ENSG00000111537", intgroup = "PTEN_SCNA_status", 
                   returnData = T)
IFNG <- IFNG %>%
  rownames_to_column(var = "ID") %>%
  mutate(Tumor_type = name, gene = "IFNG", count = log2(count))
colnames(IFNG) <- c("ID", "Count", "PTEN_SCNA_status", "Tumor_type", "Gene")

HAVCR2 <- plotCounts(dds_DESeq, gene = "ENSG00000135077", intgroup = "PTEN_SCNA_status", 
                     returnData = T)
HAVCR2 <- HAVCR2 %>%
  rownames_to_column(var = "ID") %>%
  mutate(Tumor_type = name, gene = "HAVCR2", count = log2(count))
colnames(HAVCR2) <- c("ID", "Count", "PTEN_SCNA_status", "Tumor_type", "Gene")


expression <- bind_rows(PTEN, PDCD1, CD274, CTLA4, LAG3, IDO1, IFNG, HAVCR2)
write_tsv(expression, 
            "TCGA_brain/Results/brain/expression_Brain.txt", col_names = T)

```


```{r}
p <- ggplot(expression, mapping = aes(x = PTEN_SCNA_status, y = Count, 
                                      color = PTEN_SCNA_status)) 
p2 <- p + geom_boxplot(aes(fill = PTEN_SCNA_status)) + 
  geom_point(position = position_jitter(w = 0.4,h = 0), alpha=0.3) +
  facet_grid(~ Gene) +
  ggtitle(name) +
  xlab("") +
  ylab("Transcript counts (Log2)") +
  theme(axis.text.x = element_text(size = 5),
        legend.title = element_text(size = 8),
        legend.key.height = unit(2, "mm")) +
  stat_compare_means(aes(group = PTEN_SCNA_status), 
                     paired = F, method = "t.test", 
                     label = "p.signif", hide.ns = T, ref.group = "Intact")

```

